import DM from "../../assets/Image/DMProfile.png";
import DA from "../../assets/Image/DatascienceProfile.png";
import CP from "../../assets/Image/CourseProfile.png";

export const dummyCourses = [
  {
    id: 1,
    image: CP,
    technology: "Technology",
    level: "Beginner",
    title: "Data Science & Machine Learning",
    description:
      "Master web development with HTML, CSS, JavaScript, and modern frameworks",
    institute: "Data Science Institute",
    rating: "4.9",
    reviews: "2156",
    students: "8,901",
    duration: "16 Weeks",
    price: "₹1,999",
    originalPrice: "₹4,999",
    enrolled: true,
  },
  {
    id: 2,
    image: DA,
    technology: "Technology",
    level: "Beginner",
    title: "Web Development Bootcamp",
    description:
      "Learn frontend and backend development from scratch.",
    institute: "Code Academy",
    rating: "4.8",
    reviews: "1743",
    students: "5,601",
    duration: "12 Weeks",
    price: "₹3,500",
    originalPrice: "₹5,999",
    enrolled: false,
  },
  {
    id: 3,
    image: DM,
    technology: "Marketing",
    level: "Intermediate",
    title: "Digital Marketing Essentials",
    description:
      "Learn SEO, social media marketing, and more.",
    institute: "Marketing Hub",
    rating: "4.7",
    reviews: "1890",
    students: "4,320",
    duration: "10 Weeks",
price: "₹1,999",
    originalPrice: "₹3,999",
    enrolled: true,
  },
    {
    id: 4,
   image: DA,
    technology: "Technology",
    level: "Beginner",
    title: "Web Development Bootcamp",
    description:
      "Learn frontend and backend development from scratch.",
    institute: "Code Academy",
    rating: "4.8",
    reviews: "1743",
    students: "5,601",
    duration: "12 Weeks",
    price: "₹3,500",
    originalPrice: "₹5,999",
    enrolled: false,
  },
   {
    id: 5,
    image: DM,
    technology: "Marketing",
    level: "Intermediate",
    title: "Digital Marketing Essentials",
    description:
      "Learn SEO, social media marketing, and more.",
    institute: "Marketing Hub",
    rating: "4.7",
    reviews: "1890",
    students: "4,320",
    duration: "10 Weeks",
price: "₹1,999",
    originalPrice: "₹3,999",
    enrolled: true,
  },
  {
    id: 6,
    image: CP,
    technology: "Technology",
    level: "Beginner",
    title: "Web Development Bootcamp",
    description:
      "Learn frontend and backend development from scratch.",
    institute: "Code Academy",
    rating: "4.8",
    reviews: "1743",
    students: "5,601",
    duration: "12 Weeks",
    price: "₹3,500",
    originalPrice: "₹5,999",
    enrolled: false,
  },
];
